### ISSUE TITLE
Try it live minifier

### ISSUE THREAD

**Issue by edwh** [mjmlio/gulp-mjml#37]
There's an option on the Try it Live page to minify the HTML.  It certainly seems to change things a bit, but the HTML is still full of whitespace, and doesn't look as though it's been scrunched up anything like as much as I'd expect (e.g. using https://www.willpeavy.com/minifier/).

I can use another minifier, but I wanted to check in case there are subtleties of minification in HTML emails which might mean that more aggressive minification breaks things?

**Comment by iRyusa** [comment]
We're using this one https://github.com/kangax/html-minifier ( and I think currently bugged on the try it live the minify option is bugged 🤔), we're fine with current set of default option. We try to be not too aggressive with minification because it can leads to some weird things (different width/non valid css/ ... )


I'm not sure that's the right repository to discuss it tho :)
